[package]
name = "subproc_env"
version = "0.1.0"
edition = "2024"

[dependencies]
interprocess = "2.2.3"
r2l-core = { workspace = true }
candle-core = { workspace = true }
clap = { version = "4.5.39", features = ["derive"] }
r2l-gym = { workspace = true }
