[package]
name = "r2l-tui"
version = "0.0.1"
edition = "2024"

[dependencies]
r2l-core = { workspace = true }
r2l-gym = { workspace = true }
candle-core = { workspace = true }
once_cell = "1.21.3"

[dev-dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"

[[example]]
name = "r2l-tui"
